$background = rgb(11111b) $foreground = rgb(cdd6f4) $color0 = rgb(1e1e2e) $color1 = rgb(f38ba8) $color2 = rgb(a6e3a1) $color3 = rgb(f9e2af) $color4 = rgb(89b4fa) $color5 = rgb(cba6f7) $color6 = rgb(94e2d5) $color7 = rgb(cdd6f4) $color8 = rgb(313244) $color9 = rgb(eba0ac) $color10 = rgb(fab387) $color11 = rgb(f5c2e7) $color12 = rgb(74c7ec) $color13 = rgb(f5e0dc) $color14 = rgb(b4befe) $color15 = rgb(bac2de) 

# BACKGROUND
background {
    monitor =
    path = /usr/share/backgrounds/perso/montain.jpg
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = rgb(F2F3F4)
    fail_color = rgb(fab8e4)
    fade_on_empty = false
    rounding = -1
    check_color = rgb(fab8e4)
    placeholder_text = ...
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}
